#### Importação das bibliotecas ####

In [20]:
from collections import Counter
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import LocalOutlierFactor

#### Carregando o dataset ####

In [21]:
df = pd.read_csv("data/creditcard.csv")

df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

#### Análise estatística do DataFrame ####

In [22]:
print("Análise estatística")
df.describe()

Análise estatística

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.175161e-15,3.384974e-16,-1.379537e-15,2.094852e-15,1.021879e-15,1.494498e-15,-5.620335e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.576577e-16,2.618565e-16,4.473914e-15,5.109395e-16,1.686100e-15,-3.661401e-16,-1.227452e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [24]:
print(f"Formato do dataset: {df.shape}")

Formato do dataset: (284807, 31)

Contagem de frequência das nossas classes

In [25]:
print(f"Frequência de valor na coluna: {df['Class'].value_counts()}")
print("0 = normal   /   1 = fraude")

Frequência de valor na coluna: Class
0    284315
1       492
Name: count, dtype: int64
0 = normal   /   1 = fraude

#### Padronização das features ####

As colunas 'Time' e 'Amount' são as únicas que estão numa escala diferente das demais, por isso vamos reatribuir a elas o valor de cada linha escalonizada com o Standard Scaler.

In [26]:
scaler = StandardScaler()

df[['Time', 'Amount']] = scaler.fit_transform(df[['Time', 'Amount']])

Dataset após escalonizar essas duas colunas:

In [27]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.996583,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244964,0
1,-1.996583,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342475,0
2,-1.996562,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.160686,0
3,-1.996562,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.140534,0
4,-1.996541,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073403,0

#### Definindo as features ####

In [28]:
X = df[['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23',	'V24', 'V25', 'V26', 'V27', 'V28', 'Amount']]

print("Features definidas!")

Features definidas!

### Processo de detecção de anomalias ####

##### Isolation Forest #####

Na Isolation Forest, ele realiza árvores de decisão aleatórias a fim de separar os dados, e quanto menos cortes forem precisos para um dado ser separado, mais tendência a ser uma anomalia ele tem.

###### Treinamento do modelo ######

In [ ]:
clf = IsolationForest(contamination=0.01, random_state=42) # o 'contamination' serve para a gente indicar para o modelo a porcentagem estimada de anomalias em relação ao conjunto de dados

clf.fit(X) # treinando o modelo

IsolationForest(contamination=0.01, random_state=42)

In [ ]:
predictions = clf.predict(X) # enviando as nossas features para o modelo treinado, e ele retorna um array numpy com '1' e '-1', em que '1' são os dados normais e '-1' são as anomalias
print(f"Predictions: {Counter(predictions)}") # contando quantos dados normais e quantas anomalias houveram na nossa predição

Predictions: Counter({np.int64(1): 281958, np.int64(-1): 2849})

281.958 dados normais

2.849 anomalias

###### Avaliando a performance do modelo ######

In [31]:
scores = clf.decision_function(X)
print(f"Anomaly Scores: {scores}")

Anomaly Scores: [0.19632452 0.19503303 0.10651513 ... 0.16346974 0.11631027 0.17271475]

In [32]:
predictions[predictions == 1] = 0
predictions[predictions == -1] = 1

print(f"Predictions: {Counter(predictions)}")

Predictions: Counter({np.int64(0): 281958, np.int64(1): 2849})

###### Matriz de confusão ######

In [33]:
cm = confusion_matrix(df['Class'], predictions)
print(cm)

[[281755   2560]
 [   203    289]]

281.755 verdadeiros positivos

2.560 falsos negativos

203 falsos positivos

289 verdadeiros positivos

Deixou passar 203 fraudes e deu 2.560 alarmes falsos, ou seja, não é um bom modelo.

In [34]:
target_names = ['Normal', 'Fraude']

print(classification_report(df['Class'], predictions, target_names=target_names))

              precision    recall  f1-score   support

      Normal       1.00      0.99      1.00    284315
      Fraude       0.10      0.59      0.17       492

    accuracy                           0.99    284807
   macro avg       0.55      0.79      0.58    284807
weighted avg       1.00      0.99      0.99    284807

##### Local Outlier Factor #####

O Local Outlier Factor verifica a densidade local dos pontos, ou seja, quanto menos pontos estão próximos de um, mais tendência ele tem a ser uma anomalia.

###### Treinamento do modelo ######

In [ ]:
lof = LocalOutlierFactor(n_neighbors=20, contamination=0.0017) # o 'n_neighbors' define a quantidade de vizinhos a serem verificados em um local de densidade

X_pred = lof.fit_predict(X) # treinando o modelo

In [ ]:
lof_predictions = pd.Series(X_pred) # transformando o 'X_pred' em um DataFrame para ter uma melhor manipulação
lof_predictions[lof_predictions == 1] = 0 # '0' dados normais
lof_predictions[lof_predictions == -1] = 1 # '1' anomalias

print(f"Predictions: {Counter(lof_predictions)}")

Predictions: Counter({0: 284322, 1: 485})

284.322 dados normais

485 anomalias

###### Avaliação da performance do modelo ######

In [51]:
cm_lof = confusion_matrix(df['Class'], lof_predictions)
print(cm_lof)

[[283830    485]
 [   492      0]]

Não acertou nenhuma fraude;

492 dados normais foram tratados como anomalias;

Deu 485 alarmes falsos.

In [52]:
print(classification_report(df['Class'], lof_predictions, target_names=['Normal', 'Fraude']))

              precision    recall  f1-score   support

      Normal       1.00      1.00      1.00    284315
      Fraude       0.00      0.00      0.00       492

    accuracy                           1.00    284807
   macro avg       0.50      0.50      0.50    284807
weighted avg       1.00      1.00      1.00    284807

#### Conclusão ####

Tanto Isolation Forest quanto Local Outlier Factor tiveram dificuldade em detectar as fraudes nesse dataset. Isso sugere que as fraudes desse dataset não são bem "isoladas" nem "de baixa densidade" no espaço de features.

Pra esse tipo de problema, técnicas de aprendizado supervisionado seriam mais adequadas.